apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/1-java-springboot/base
- components/1-nodejs/base
- components/wild-west-backend/base
- components/wild-west-frontend/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
