apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wild-west-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wild-west-backend
    app.kubernetes.io/part-of: purple-mermaid-app
  name: wild-west-backend
  namespace: pdave
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: wild-west-backend
status:
  loadBalancer: {}
